controller_manager:
  ros__parameters:
    update_rate: 100
    # use_sim_time: true

    diffbot_base_controller:
      type: diff_drive_controller/DiffDriveController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

diffbot_base_controller:
  ros__parameters:
    left_wheel_names: ['Revolute_5']
    right_wheel_names: ['Revolute_4']
    wheel_separation: 0.285
    #wheels_per_side: 1  # actually 2, but both are controlled by 1 signal
    wheel_radius: 0.05

    publish_rate: 50.0
    odom_frame_id: odom
    base_frame_id: base_link
    pose_covariance_diagonal : [0.001, 0.001, 0.001, 0.001, 0.001, 0.01]
    twist_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.01]

    use_stamped_vel: false
    enable_odom_tf: true

